apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acp-sa-import
nameSuffix: -devopstest11
resources:
  - ../../../../base/job.yaml
configMapGenerator:
  - name: envs
    literals:
      - TENANT_ID=saidp-devopstest11
      - ORGANIZATION=devopstest11
    files:
      - JWKS_KEYS=jwks.json
      - CA=../saidp-intermediate-cas.pem
